/**
 * The Research Atlas data, generated by `website/scripts/generate_atlas.py`
 * from the registry export (`agenticresearch/py/registry.py export`) plus the
 * website-side content under `website/content/atlas/`. Every public research
 * page is a projection of this one document; `tests/test_atlas_data.py`
 * keeps the committed JSON equal to a fresh run.
 */
import rawData from "../generated/atlas.json";

export type Provenance =
  | "established"
  | "derived"
  | "proved"
  | "proved_new"
  | "measured"
  | "counterexample"
  | "open"
  | "verification";

export type EntityKind = "result" | "question" | "counterexample" | "evidence" | "audit";

export type EdgeType =
  | "rests_on"
  | "enables"
  | "raises"
  | "verified_by"
  | "converse_fails"
  | "refuted_by"
  | "bounded_by"
  | "cites";

export interface VocabularyEntry {
  description: string;
  id: string;
  label: string;
}

export interface LevelEntry extends VocabularyEntry {
  short: string;
}

export interface CriterionEntry extends VocabularyEntry {
  lane: string;
  primary?: boolean;
  short: string;
}

export interface FileRef {
  path: string;
  url: string;
}

export interface ReportRef {
  file: string;
  kind: "audit" | "formalization";
  url: string;
  verdict: string | null;
}

export interface PriorArtAudit {
  date: string | null;
  sources: {name: string; text: string}[];
  url: string;
}

export interface Claim {
  artifact: FileRef | null;
  assumptions: string[];
  audit: ReportRef | null;
  chapter: {file: string; label: string; section: string | null; slug: string} | null;
  criterion: string[];
  enforcedBy: string[];
  id: string;
  implementedBy: string[];
  kind: EntityKind;
  level: string;
  literature: string[];
  machineChecked: {
    declaration: string;
    proof: FileRef;
    spec: FileRef;
    statementAudit: ReportRef | null;
    system: string;
  } | null;
  note: string | null;
  parked: boolean;
  priorArt: PriorArtAudit[];
  proof: {file: string; label: string | null; markdown: string; title: string; url: string} | null;
  provenance: Provenance;
  publicationStatus: string;
  role: string | null;
  scope: string | null;
  searchStatus: string | null;
  slug: string;
  statement: string;
  status: string;
  strip: string | null;
  theme: string | null;
  title: string;
}

export interface Fixture {
  K: number;
  citedBy: {claim: string; type: "refuted_by" | "bounded_by"}[];
  consequences: string[];
  criterion: string[];
  date: string | null;
  dimension: number;
  falsifies: string;
  id: string;
  labelsAfter: number[] | null;
  labelsBefore: number[];
  level: string;
  note: string | null;
  nuisance: number[] | null;
  objectiveAfter: string | number | null;
  objectiveBefore: string | number | null;
  poi: number[] | null;
  refusal: {reason: string; remedy: string; trigger: string} | null;
  /** Exact rationals as strings ("1/2") or numbers; d=1 fixtures are flat. */
  scores: (string | number)[][] | (string | number)[];
  slug: string;
  url: string;
  verification: {method: string | null; notes: string | null};
  weights: (string | number)[];
}

export interface Annotation {
  fields: Record<string, string>;
  heading: string;
  links: {label: string; url: string}[];
  prose: string;
  tradition: string;
}

export interface Paper {
  annotation: Annotation | null;
  area: string | null;
  arxiv: string | null;
  authors: {name: string; slug: string}[];
  citedBy: string[];
  doi: string | null;
  fullAuthors: string[];
  key: string;
  note: string | null;
  pdf: string | null;
  relevantTo: string[];
  slug: string;
  title: string;
  tradition: string | null;
  year: number | null;
}

export interface Author {
  name: string;
  papers: string[];
  slug: string;
}

export interface Tradition {
  label: string;
  notes: Annotation[];
  papers: string[];
  slug: string;
  title: string;
}

export interface Chapter {
  file: string;
  label: string;
  sections: {claims: string[]; label: string | null; title: string}[];
  slug: string;
  url: string;
}

export interface Theme {
  claims: string[];
  label: string;
  programme: string;
  slug: string;
  summary: string;
}

export interface Strip {
  claims: string[];
  id: string;
  label: string;
}

export interface Edge {
  source: string;
  target: string;
  type: EdgeType;
}

export interface Layout {
  bands: {id: string; y0: number; y1: number}[];
  columns: {level: string; x: number}[];
  height: number;
  positions: Record<string, {lane: string; x: number; y: number}>;
}

export interface LibraryObject {
  claims: string[];
  group: string;
  /** Display text: may name several symbols or a method. */
  name: string;
  role: string;
  /** The public `scorequant` symbols the name refers to; validated by the generator. */
  symbols: string[];
}

export interface LibraryRefusal {
  claims: string[];
  code: string;
  reason: string;
  remedy: string;
  trigger: string;
}

export interface FormalModule {
  claims: string[];
  module: string;
  partial?: boolean;
  proof: FileRef | null;
  result: string;
  spec: FileRef | null;
}

export interface Atlas {
  authors: Record<string, Author>;
  chapters: Chapter[];
  claims: Record<string, Claim>;
  edges: Edge[];
  fixtures: Record<string, Fixture>;
  formal: {axioms: string[]; chain: FormalModule[]; outside: string[]; readme: string};
  frontier: string[];
  headline: string[];
  layout: Layout;
  library: {objects: LibraryObject[]; refusals: LibraryRefusal[]};
  papers: Record<string, Paper>;
  schemaVersion: number;
  strips: Strip[];
  themes: Theme[];
  traditions: Tradition[];
  vocabulary: {
    criteria: CriterionEntry[];
    edgeTypes: VocabularyEntry[];
    lanes: VocabularyEntry[];
    levels: LevelEntry[];
    provenance: VocabularyEntry[];
  };
}

export const atlas = rawData as unknown as Atlas;
