import rawShowcase from "../generated/showcase-data.json";

export interface ShowcaseDataset {
  citation: string;
  fixtureCells: number;
  heldOutPatients: number[];
  license: string;
  licenseUrl: string;
  markers: string[];
  name: string;
  patients: number;
  populations: string[];
  referencePatients: number[];
  repository: string;
  studyCells: number;
  upstreamEvents: number;
}

export interface MarkerSeries {
  density: number[];
  population: string;
}

export interface MarkerPanel {
  edges: number[];
  marker: string;
  series: MarkerSeries[];
}

export interface PatientComposition {
  fractions: number[];
  patient: number;
  role: string;
}

export interface MethodPoint {
  bins: number;
  heldOutEfficiency: number | null;
  macroRmse: number;
  minimumBinCount: number | null;
}

export interface MethodSeries {
  isScoreQuant: boolean;
  key: string;
  label: string;
  points: MethodPoint[];
}

export interface BinCompositionRow {
  bin: number;
  composition: number[];
  dominant: string;
}

export interface BinComposition {
  bins: number;
  populations: string[];
  rows: BinCompositionRow[];
}

export interface PatientEstimate {
  binned: number[];
  expert: number[];
  patient: number;
  unbinned: number[];
}

export interface ShowcaseData {
  binComposition: BinComposition;
  comparison: {
    budgets: number[];
    methods: MethodSeries[];
    unbinnedBaseline: {label: string; macroRmse: number; perClassRmse: number[]};
  };
  dataset: ShowcaseDataset;
  exploration: {markerScale: string; markers: MarkerPanel[]; patients: PatientComposition[]};
  headline: {
    bins: number;
    heldOutEfficiency: number;
    macroRmse: number;
    unbinnedMacroRmse: number;
  };
  patientEstimates: PatientEstimate[];
  scoreSchema: {parameters: string[]};
}

/**
 * Generated by `website/scripts/generate_showcase.py` from committed artifacts.
 * Never edit by hand; run `pnpm generate:showcase`.
 */
export const showcaseData = rawShowcase as unknown as ShowcaseData;
